# Generated by Django 5.0.3 on 2024-04-18 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cntry_mstr',
            name='country_code',
            field=models.CharField(max_length=50, null=True, unique=True),
        ),
    ]
