# Generated by Django 5.0.3 on 2024-04-18 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0002_cntry_mstr_country_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cntry_mstr',
            name='country_code',
            field=models.CharField(max_length=150, null=True, unique=True),
        ),
    ]
