# Generated by Django 5.0.3 on 2024-04-23 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0005_document_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nationality',
            name='N_name',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
