# Generated by Django 5.0.3 on 2024-03-13 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EmpManagement', '0002_alter_emp_master_emp_mobile_number_1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='emp_master',
            name='is_ess',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
    ]
