# Generated by Django 5.0.3 on 2024-03-22 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EmpManagement', '0003_emp_master_is_ess'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emp_master',
            name='emp_gender',
            field=models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], max_length=10, null=True),
        ),
    ]
