# Generated by Django 5.0.3 on 2024-03-22 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EmpManagement', '0006_alter_emp_master_emp_mobile_number_1'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emp_master',
            name='emp_marital_status',
            field=models.CharField(blank=True, choices=[('M', 'Married'), ('S', 'Single'), ('D', 'Other')], max_length=10, null=True),
        ),
    ]
