# Generated by Django 5.0.3 on 2024-03-27 06:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('EmpManagement', '0008_dynamicfield'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DynamicField',
        ),
    ]
