# Generated by Django 5.0.3 on 2024-03-27 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EmpManagement', '0009_delete_dynamicfield'),
    ]

    operations = [
        migrations.AddField(
            model_name='emp_master',
            name='custom_fields',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
