# Generated by Django 5.0.3 on 2024-03-27 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EmpManagement', '0011_alter_emp_master_custom_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emp_master',
            name='custom_fields',
            field=models.JSONField(default=dict, null=True),
        ),
    ]
