# Generated by Django 5.0.3 on 2024-03-28 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EmpManagement', '0014_emp_master_user_defined_fields_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='emp_master',
            options={},
        ),
        migrations.RemoveField(
            model_name='emp_master',
            name='user_defined_fields',
        ),
        migrations.AddField(
            model_name='emp_master',
            name='custom_fields',
            field=models.JSONField(default=dict, null=True),
        ),
    ]
