# Generated by Django 5.0.3 on 2024-03-28 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EmpManagement', '0016_alter_emp_master_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='emp_master',
            options={},
        ),
        migrations.AddField(
            model_name='emp_master',
            name='custom_fields',
            field=models.JSONField(default=dict, null=True),
        ),
        migrations.DeleteModel(
            name='UserDefinedField',
        ),
    ]
