# Generated by Django 5.0.3 on 2024-03-28 09:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EmpManagement', '0017_alter_emp_master_options_emp_master_custom_fields_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emp_master',
            name='custom_fields',
        ),
        migrations.CreateModel(
            name='CustomField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('field_type', models.CharField(choices=[('char', 'CharField'), ('date', 'DateField'), ('email', 'EmailField'), ('boolean', 'BooleanField')], max_length=20)),
                ('EmpMasters', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='custom_fields', to='EmpManagement.emp_master')),
            ],
        ),
    ]
