# Generated by Django 5.0.3 on 2024-03-28 10:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EmpManagement', '0019_remove_customfield_empmasters_customfield_emp_master_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customfield',
            name='emp_master',
        ),
        migrations.RemoveField(
            model_name='emp_master',
            name='custom_fields',
        ),
        migrations.AddField(
            model_name='emp_master',
            name='custom_field',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='emp_masters_customfield', to='EmpManagement.customfield'),
        ),
    ]
