# Generated by Django 5.0.3 on 2024-03-28 12:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EmpManagement', '0021_customfield_content_type_customfield_default_value_and_more'),
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='customfield',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='emp_master',
            name='custom_field',
        ),
        migrations.AlterField(
            model_name='customfield',
            name='field_type',
            field=models.CharField(choices=[('char', 'CharField'), ('text', 'TextField'), ('integer', 'IntegerField'), ('float', 'FloatField'), ('boolean', 'BooleanField'), ('date', 'DateField'), ('datetime', 'DateTimeField')], max_length=20),
        ),
        migrations.AlterField(
            model_name='customfield',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.CreateModel(
            name='CustomFieldValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value_char', models.CharField(blank=True, max_length=200, null=True)),
                ('value_text', models.TextField(blank=True, null=True)),
                ('value_integer', models.IntegerField(blank=True, null=True)),
                ('value_float', models.FloatField(blank=True, null=True)),
                ('value_boolean', models.BooleanField(blank=True, null=True)),
                ('value_date', models.DateField(blank=True, null=True)),
                ('value_datetime', models.DateTimeField(blank=True, null=True)),
                ('object_id', models.PositiveIntegerField()),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='EmpManagement.customfield')),
            ],
        ),
        migrations.RemoveField(
            model_name='customfield',
            name='content_type',
        ),
        migrations.RemoveField(
            model_name='customfield',
            name='default_value',
        ),
        migrations.RemoveField(
            model_name='customfield',
            name='field_choices',
        ),
        migrations.RemoveField(
            model_name='customfield',
            name='is_required',
        ),
        migrations.RemoveField(
            model_name='customfield',
            name='mask',
        ),
    ]
