# Generated by Django 5.0.3 on 2024-04-01 04:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('EmpManagement', '0023_customfield_content_type_customfield_default_value_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emp_master',
            name='custom_field',
        ),
        migrations.DeleteModel(
            name='CustomField',
        ),
    ]
