# Generated by Django 5.0.3 on 2024-04-01 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EmpManagement', '0025_customfield'),
    ]

    operations = [
        migrations.AddField(
            model_name='customfield',
            name='data_type',
            field=models.CharField(blank=True, choices=[('text', 'Text'), ('integer', 'Integer'), ('float', 'Float'), ('date', 'Date'), ('boolean', 'Boolean')], max_length=20, null=True),
        ),
    ]
