# Generated by Django 5.0.3 on 2024-04-01 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EmpManagement', '0026_customfield_data_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customfield',
            name='data_type',
            field=models.CharField(blank=True, choices=[('char', 'CharField'), ('date', 'DateField'), ('email', 'EmailField'), ('boolean', 'BooleanField')], max_length=20, null=True),
        ),
    ]
