# Generated by Django 5.0.3 on 2024-04-02 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EmpManagement', '0029_empfamily_customfield'),
    ]

    operations = [
        migrations.AddField(
            model_name='emp_family',
            name='ef_member_no',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
    ]
