# Generated by Django 5.0.3 on 2024-04-02 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EmpManagement', '0030_emp_family_ef_member_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emp_family',
            name='ef_member_no',
            field=models.CharField(blank=True, max_length=50, unique=True),
        ),
    ]
