# Generated by Django 5.0.3 on 2024-04-03 04:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EmpManagement', '0032_alter_emp_family_ef_member_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='empjobhistory',
            name='emp_jh_no',
            field=models.CharField(blank=True, default=None, max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='emp_customfield',
            name='emp_master',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='custom_fields', to='EmpManagement.emp_master'),
        ),
        migrations.AlterField(
            model_name='empfamily_customfield',
            name='emp_family',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fam_custom_fields', to='EmpManagement.emp_family'),
        ),
        migrations.CreateModel(
            name='EmpJobHistory_CustomField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_name', models.CharField(max_length=100)),
                ('field_value', models.CharField(max_length=255)),
                ('data_type', models.CharField(blank=True, choices=[('char', 'CharField'), ('date', 'DateField'), ('email', 'EmailField'), ('integer', 'IntegerField'), ('boolean', 'BooleanField')], max_length=20, null=True)),
                ('emp_jobhistory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='custom_fields', to='EmpManagement.empjobhistory')),
            ],
        ),
    ]
