# Generated by Django 5.0.3 on 2024-04-03 04:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('EmpManagement', '0033_empjobhistory_emp_jh_no_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='empjobhistory_customfield',
            old_name='emp_jobhistory',
            new_name='emp_job_history',
        ),
    ]
