# Generated by Django 5.0.3 on 2024-04-03 05:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EmpManagement', '0034_rename_emp_jobhistory_empjobhistory_customfield_emp_job_history'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empjobhistory_customfield',
            name='emp_job_history',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jobhistory_customfields', to='EmpManagement.empjobhistory'),
        ),
        migrations.CreateModel(
            name='EmpQualification_CustomField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_name', models.CharField(max_length=100)),
                ('field_value', models.CharField(max_length=255)),
                ('data_type', models.CharField(blank=True, choices=[('char', 'CharField'), ('date', 'DateField'), ('email', 'EmailField'), ('integer', 'IntegerField'), ('boolean', 'BooleanField')], max_length=20, null=True)),
                ('emp_qualification', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='custom_fields', to='EmpManagement.empqualification')),
            ],
        ),
    ]
