# Generated by Django 5.0.3 on 2024-04-03 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EmpManagement', '0035_alter_empjobhistory_customfield_emp_job_history_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='empqualification',
            name='emp_sl_no',
            field=models.CharField(blank=True, default=None, max_length=50, null=True, unique=True),
        ),
    ]
