# Generated by Django 5.0.3 on 2024-04-03 07:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EmpManagement', '0036_empqualification_emp_sl_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='emp_documents',
            name='emp_sl_no',
            field=models.CharField(blank=True, default=None, max_length=50, null=True, unique=True),
        ),
        migrations.CreateModel(
            name='EmpDocuments_CustomField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_name', models.CharField(max_length=100)),
                ('field_value', models.CharField(max_length=255)),
                ('data_type', models.CharField(blank=True, choices=[('char', 'CharField'), ('date', 'DateField'), ('email', 'EmailField'), ('integer', 'IntegerField'), ('boolean', 'BooleanField')], max_length=20, null=True)),
                ('emp_documents', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='custom_fields', to='EmpManagement.emp_documents')),
            ],
        ),
    ]
