# Generated by Django 5.0.3 on 2024-04-05 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EmpManagement', '0037_emp_documents_emp_sl_no_empdocuments_customfield'),
    ]

    operations = [
        migrations.AddField(
            model_name='emp_customfield',
            name='dropdown_values',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='emp_customfield',
            name='data_type',
            field=models.CharField(blank=True, choices=[('char', 'CharField'), ('date', 'DateField'), ('email', 'EmailField'), ('integer', 'IntegerField'), ('boolean', 'BooleanField'), ('dropdown', 'DropdownField')], max_length=20, null=True),
        ),
    ]
