# Generated by Django 5.0.3 on 2024-04-05 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EmpManagement', '0038_emp_customfield_dropdown_values_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emp_customfield',
            name='data_type',
            field=models.CharField(blank=True, choices=[('char', 'CharField'), ('date', 'DateField'), ('email', 'EmailField'), ('integer', 'IntegerField'), ('boolean', 'BooleanField'), ('dropdown', 'DropdownField'), ('text', 'TextField')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='emp_customfield',
            name='dropdown_values',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
