# Generated by Django 5.0.3 on 2024-04-05 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EmpManagement', '0039_alter_emp_customfield_data_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emp_customfield',
            name='dropdown_values',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
