# Generated by Django 5.0.3 on 2024-04-06 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EmpManagement', '0040_alter_emp_customfield_dropdown_values'),
    ]

    operations = [
        migrations.AddField(
            model_name='emp_customfield',
            name='radio_values',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='emp_customfield',
            name='data_type',
            field=models.CharField(blank=True, choices=[('char', 'CharField'), ('date', 'DateField'), ('email', 'EmailField'), ('integer', 'IntegerField'), ('boolean', 'BooleanField'), ('dropdown', 'DropdownField'), ('text', 'TextField'), ('radio', 'RadioButtonField')], max_length=20, null=True),
        ),
    ]
