# Generated by Django 5.0.3 on 2024-04-12 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EmpManagement', '0046_empdocuments_customfield_dropdown_values_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emp_customfield',
            name='field_value',
            field=models.TextField(),
        ),
    ]
