# Generated by Django 5.0.3 on 2024-04-19 09:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0005_document_type'),
        ('EmpManagement', '0047_alter_emp_customfield_field_value'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emp_documents',
            name='emp_doc_name',
        ),
        migrations.AddField(
            model_name='emp_documents',
            name='emp_doc_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Core.document_type'),
        ),
    ]
