# Generated by Django 5.0.3 on 2024-04-23 09:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0006_alter_nationality_n_name'),
        ('EmpManagement', '0048_remove_emp_documents_emp_doc_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emp_master',
            name='emp_nationality',
        ),
        migrations.AddField(
            model_name='emp_master',
            name='emp_nationality_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Core.nationality'),
        ),
    ]
