# Generated by Django 5.0.3 on 2024-04-24 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EmpManagement', '0049_remove_emp_master_emp_nationality_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emp_customfield',
            name='selectbox_values',
        ),
        migrations.AlterField(
            model_name='emp_customfield',
            name='data_type',
            field=models.CharField(blank=True, choices=[('dropdown', 'DropdownField'), ('radio', 'RadioButtonField')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='emp_customfield',
            name='field_value',
            field=models.TextField(blank=True, null=True),
        ),
    ]
