# Generated by Django 5.0.3 on 2024-04-24 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EmpManagement', '0050_remove_emp_customfield_selectbox_values_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='empdocuments_customfield',
            name='selectbox_values',
        ),
        migrations.RemoveField(
            model_name='empfamily_customfield',
            name='selectbox_values',
        ),
        migrations.RemoveField(
            model_name='empjobhistory_customfield',
            name='selectbox_values',
        ),
        migrations.RemoveField(
            model_name='empqualification_customfield',
            name='selectbox_values',
        ),
        migrations.AlterField(
            model_name='empdocuments_customfield',
            name='data_type',
            field=models.CharField(blank=True, choices=[('dropdown', 'DropdownField'), ('radio', 'RadioButtonField')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='empdocuments_customfield',
            name='field_value',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='empfamily_customfield',
            name='data_type',
            field=models.CharField(blank=True, choices=[('dropdown', 'DropdownField'), ('radio', 'RadioButtonField')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='empfamily_customfield',
            name='field_value',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='empjobhistory_customfield',
            name='data_type',
            field=models.CharField(blank=True, choices=[('dropdown', 'DropdownField'), ('radio', 'RadioButtonField')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='empjobhistory_customfield',
            name='field_value',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='empqualification_customfield',
            name='data_type',
            field=models.CharField(blank=True, choices=[('dropdown', 'DropdownField'), ('radio', 'RadioButtonField')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='empqualification_customfield',
            name='field_value',
            field=models.TextField(blank=True, null=True),
        ),
    ]
