# Generated by Django 5.0.3 on 2024-04-24 09:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('EmpManagement', '0051_remove_empdocuments_customfield_selectbox_values_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='emp_family',
            old_name='ef_member_no',
            new_name='ef_sl_no',
        ),
    ]
