# Generated by Django 5.0.3 on 2024-04-24 09:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('EmpManagement', '0052_rename_ef_member_no_emp_family_ef_sl_no'),
    ]

    operations = [
        migrations.RenameField(
            model_name='empjobhistory',
            old_name='emp_jh_no',
            new_name='emp_sl_no',
        ),
    ]
