# Generated by Django 5.0.3 on 2024-04-25 06:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('EmpManagement', '0053_rename_emp_jh_no_empjobhistory_emp_sl_no'),
    ]

    operations = [
        migrations.RenameField(
            model_name='emp_master',
            old_name='emp_login_id',
            new_name='emp_code',
        ),
    ]
