# Generated by Django 5.0.3 on 2024-04-25 07:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EmpManagement', '0054_rename_emp_login_id_emp_master_emp_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.BooleanField(default=False)),
                ('marketing', models.BooleanField(default=False)),
                ('programming_language', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='SkillValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=100)),
                ('skill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='EmpManagement.skill')),
            ],
        ),
    ]
