# Generated by Django 5.0.3 on 2024-04-25 09:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('EmpManagement', '0055_skill_skillvalue'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='skillvalue',
            name='skill',
        ),
        migrations.DeleteModel(
            name='Skill',
        ),
        migrations.DeleteModel(
            name='SkillValue',
        ),
    ]
