# Generated by Django 5.0.3 on 2024-04-25 09:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EmpManagement', '0056_remove_skillvalue_skill_delete_skill_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.BooleanField(default=False)),
                ('marketing', models.BooleanField(default=False)),
                ('programming_language', models.BooleanField(default=False)),
                ('emp_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emp_skill', to='EmpManagement.emp_master')),
            ],
        ),
        migrations.CreateModel(
            name='SkillValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=100)),
                ('skill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='EmpManagement.skill')),
            ],
        ),
    ]
