# Generated by Django 5.0.3 on 2024-04-25 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EmpManagement', '0057_skill_skillvalue'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='skill',
            name='language',
        ),
        migrations.RemoveField(
            model_name='skill',
            name='marketing',
        ),
        migrations.RemoveField(
            model_name='skill',
            name='programming_language',
        ),
        migrations.AddField(
            model_name='skill',
            name='selected_field',
            field=models.CharField(choices=[('language', 'Language'), ('marketing', 'Marketing'), ('programming_language', 'Programming Language')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='skill',
            name='value',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
