# Generated by Django 5.0.3 on 2024-04-27 03:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('EmpManagement', '0058_remove_skill_language_remove_skill_marketing_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='skillvalue',
            name='skill',
        ),
        migrations.DeleteModel(
            name='Skill',
        ),
        migrations.DeleteModel(
            name='SkillValue',
        ),
    ]
