# Generated by Django 5.0.3 on 2024-04-27 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EmpManagement', '0059_remove_skillvalue_skill_delete_skill_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Skills_Master',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(blank=True, max_length=100, null=True)),
                ('marketing', models.CharField(blank=True, max_length=100, null=True)),
                ('programming_language', models.CharField(blank=True, max_length=100, null=True)),
                ('value', models.JSONField(blank=True, null=True)),
            ],
        ),
    ]
