# Generated by Django 5.0.3 on 2024-04-27 09:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EmpManagement', '0061_delete_skills_master'),
    ]

    operations = [
        migrations.CreateModel(
            name='Skills_Master',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(blank=True, max_length=100, null=True)),
                ('marketing', models.CharField(blank=True, max_length=100, null=True)),
                ('programming_language', models.CharField(blank=True, max_length=100, null=True)),
                ('value', models.JSONField(blank=True, null=True)),
                ('emp_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emp_skills', to='EmpManagement.emp_master')),
            ],
        ),
    ]
