# Generated by Django 5.0.3 on 2024-04-29 06:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('EmpManagement', '0062_skills_master'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Skills_Master',
        ),
    ]
