# Generated by Django 5.0.3 on 2024-04-30 03:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EmpManagement', '0066_remove_employeeskill_language_skill_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employeeskill',
            name='language_skill',
        ),
        migrations.AddField(
            model_name='employeeskill',
            name='language_skill',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='EmpManagement.languageskill'),
        ),
    ]
