# Generated by Django 5.0.3 on 2024-05-04 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EmpManagement', '0067_remove_employeeskill_language_skill_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeExcelFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('excel_file', models.FileField(blank=True, null=True, upload_to='employee_excel/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
