# Generated by Django 5.0.3 on 2024-05-04 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EmpManagement', '0068_employeeexcelfile'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeeexcelfile',
            name='file_name',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
