# Generated by Django 5.0.3 on 2024-03-11 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OrganisationManager', '0002_brnch_mstr_br_created_by_brnch_mstr_br_updated_by_and_more'),
        ('UserManagement', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='branches',
            field=models.ManyToManyField(blank=True, null=True, to='OrganisationManager.brnch_mstr'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='companies',
            field=models.ManyToManyField(blank=True, null=True, to='OrganisationManager.cmpny_mastr'),
        ),
    ]
